---
title: "535 Homework 5"
author: "Will Finical"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, error = FALSE, message = FALSE, include = TRUE)
```

## Baltimore Homicides

```{r packages}
library(tidyverse)
library(lubridate)
library(dplyr)
library(scales)
library(ggthemes)
library(readr)
```

```{r data}
homicides <- read_csv("homicide-data.csv")
homicides <- homicides %>%
  unite("city_name", c("city", "state"), sep = ", ", remove = FALSE)
```

```{r cleaning}
Baltimore <- homicides %>%
  filter(city == "Baltimore") %>%
  mutate(date = ymd(reported_date)) %>%
  mutate(month = ym(paste0(year(date), month(date)))) %>%
  group_by(month) %>%
  summarise(count = n()) %>%
  ungroup()

```

```{r figure data}
fig_df <- Baltimore %>%
  mutate(month_name = month(month, label = TRUE)) %>%
  mutate(weather = case_when(month_name == "Jan" | month_name == "Feb" | 
                               month_name == "Mar" | month_name == "Apr" |
                               month_name == "Nov" | month_name == "Dec"
                             ~ "Winter",
                             month_name == "Jun" | month_name == "Jul" | 
                               month_name == "Aug" | month_name == "Sep" |
                               month_name == "May" | month_name == "Oct"
                             ~ "Summer"))

```

```{r freddie grey}
grey <- homicides %>%
  filter(victim_last == "GREY" & victim_first == "FREDDIE CARLOS") %>%
  mutate(date = ymd(reported_date)) %>%
  select(victim_last, victim_first, date)

```

```{r plot}
fig_df %>%
  ggplot(aes(x=month, y=count)) +
  geom_col(aes(fill = weather)) +
  geom_smooth(span = 0.2, se = FALSE) +
  scale_fill_manual(values = c("grey88", "lightblue")) +
  ggtitle("Homicides in Baltimore, MD") +
  xlab("Date") +
  ylab("Monthly homicides")
```
